### ISSUE TITLE
Hangs when trying to fetch non existing hash

### ISSUE THREAD

**Issue by rohitkhatri** [ipfs/js-ipfs-api#862] opened 2018-09-22 09:21 UTC
When I try to fetch a non existing `hash`, the sdk hangs.

Here's what my code looks like:

```javascript
const ipfsAPI = require('ipfs-api');
const api = ipfsAPI('/ip4/127.0.0.1/tcp/5001');
```

When I try to fetch a valid address using the below code works fine:

```javascript
api.ls('QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVa')
    .then(response => console.log('File retrieved:', response))
    .catch(error => console.log('Error while retrieveing file:', error));
```

But when I try to fetch a non existing address, It hangs and doesn't stop.
	
``` javascript
sdk.sdk.files.get('QmQLXHs7K98JNQdWrBB2cQLJahPhmupbDjRuH1b9ibmwVV')
    .then(response => console.log(response))
    .catch(err => console.log(err));
```

**Comment by alanshaw** [comment] 2018-10-15 17:46
Hi @rohitkhatri, thanks for taking the time to submit this issue. Currently requests are not cancelable. We would like them to be cancelable in the future. If you're keen to have a go at this problem then please submit a PR and/or shout if you would like some help getting started. For now I'm going to close this as a dupe of https://github.com/ipfs/js-ipfs-api/issues/694

**Closed by alanshaw** 2018-10-15 17:46 UTC
