### ISSUE TITLE
findprovs returns object or string

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs-api#76] opened 2015-10-18 07:10 UTC
using the method `ipfs.dht.findprovs` in node environment does not work like one would expect. Using the following code:
```
var ipfsAPI = require('ipfs-api')

var ipfs = ipfsAPI('localhost', '5001')

const hash = "QmXFmCEhamPHvpbzQ3HMFABrpAXgE7D9jzp6QtvyC8Xp55"

ipfs.dht.findprovs(hash, (err, res) => {
	if(err) throw err
	console.log(res)
	console.log(typeof res)
	console.log("Streamable?", !!res.readable)
	console.log('So what to do with `res` here?')
})
```

I get the following output sometimes (which works correctly):
```
object
Streamable? false
So what to do with `res` here?
```
but other times, it returns this (which is neither streamable or valid json)
```
string
Streamable? false
So what to do with `res` here?
```

Originally open issue https://github.com/ipfs/go-ipfs/issues/1851 on go-ipfs but seems to be a bug in this library.

**Comment by VictorBjelkholm** [comment] 2015-10-18 13:02
Tried using node-ipfs-api in browser and seems to always return a string of json stream... Not sure how to handle this. Take a look here for quick demo: https://github.com/VictorBjelkholm/webpack-node-ipfs-api-demo/commit/c3dc5e229d61bd76f7a7ddf0d280ab56f6adf5c5

**Comment by diasdavid** [comment] 2015-10-18 19:19
following the IRC discussion -> We need proper Node.js and Browser tests, testing every API call, so that the interface gets polished (https://github.com/ipfs/node-ipfs-api/issues/57), otherwise it will feel that we are always chasing one more little thing.

If someone wants to go ahead and bring that, it will be very appreciated :)

**Comment by fazo96** [comment] 2015-11-10 15:11
I'm building an application on top IPFS and just ran into this problem. I read a little bit and if I understand correctly this bug will be fixed by solving #87 right?

Sorry to bother, just trying to get an estimate for the solution

**Comment by diasdavid** [comment] 2015-11-10 16:59
@fazo96 right now, this depends on what the API returns, if the IPFS node decides that has enough stuff to stream it, js-ipfs-api will return a stream, otherwise it will return a String, the decision is made on this flag - https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L63

@whyrusleeping is there any option to choose the mode explicitly?

**Comment by Dignifiedquire** [comment] 2015-11-10 17:08
I think there should be explicit options so api users can decide how they want to consume the results.

**Comment by VictorBjelkholm** [comment] 2015-11-10 19:00
@Dignifiedquire in that case, we should provide both ability to set stream/object in all methods and for individual ones.

**Comment by Dignifiedquire** [comment] 2015-11-10 19:17
@VictorBjelkholm exactly, so that it's predictable,  at the moment it's more guessing than anything.

**Comment by diasdavid** [comment] 2015-11-18 15:20
Is this still a issue with the latest changes? Could you confirm @VictorBjelkholm ?

**Comment by Dignifiedquire** [comment] 2015-11-18 15:41
Still an issue in the browser

**Comment by Dignifiedquire** [comment] 2015-11-18 15:41
Sorry, the issue is that some commands return an array and some return a single object depending if run from the browser or from node

**Comment by fazo96** [comment] 2015-11-19 18:41
This is still an issue on the latest version as of now. Findprovs returns a string with multiple json documents and there's no easy way to parse it because you would have to cut it when a document finishes and another one starts, I don't think it should be like that.

Maybe return an array of strings or a stream where each element is a parsable json?

**Comment by diasdavid** [comment] 2015-11-19 19:04
@fazo96 are you using IPFS 0.3.9? That sounds like IPFS 0.3.8 (which didn't use ndjson)

**Comment by fazo96** [comment] 2015-11-19 19:20
I'm using IPFS 0.3.9 and js-ipfs-api 2.9.0 (just updated it). I'm afraid the problem remains, but I guess I can apply ndjson.parse() myself so it's not a big deal

**Comment by Dignifiedquire** [comment] 2015-11-19 21:36
The issue is two fold, 1) go-ipfs returns a different format in the browser 2) that format is invalid json, so it has to first be fixed there: https://github.com/ipfs/go-ipfs/issues/1978

**Comment by Dignifiedquire** [comment] 2015-11-19 21:43
Turns out this is a bug on our side..We are not properly all headers, resulting in the wrong handling of the response.

**Comment by Dignifiedquire** [comment] 2015-11-19 22:11
Real problem

> because of the great spec on “fetch” https://fetch.spec.whatwg.org/#concept-filtered-response-cors when doing cross origin requests and I want to access custom headers on the request they need to be listed by the server using the header field “Access-Control-Allow-Headers”: https://fetch.spec.whatwg.org/#http-access-control-expose-headers

**Closed** 2015-11-21 11:53 UTC
Labels: bug, bug-upstream
