### ISSUE TITLE
ipfs.files.add: cb is not a function

### ISSUE THREAD

**Issue by chpio** [ipfs/js-ipfs-api#308] opened 2016-07-01 13:49 UTC
> TypeError: cb is not a function - TypeError: cb is not a function
> at Object.add (/usr/src/app/node_modules/ipfs-api/lib/api/add.js:16:14)

using *Promise*s

**Comment by nginnever** [comment] 2016-07-01 22:25
Hello chpio! Thanks for pointing this out. Could you describe a test case when this error is thrown? Or what you are trying to add. I believe that promise should reject an error there when you provide add with invalid input.

We have a test case here in interface-ipfs-core that tests ```files.add``` promise adding a buffer. 

https://github.com/ipfs/interface-ipfs-core/blob/master/src/files.js#L138

**Comment by chpio** [comment] 2016-07-02 07:18
https://github.com/ipfs/js-ipfs-api/blob/master/src/api/add.js#L18

this code can only work with a cb if Promises are used there is no cb passed in.

**Comment by diasdavid** [comment] 2016-07-02 14:14
Fixed on https://github.com/ipfs/js-ipfs-api/pull/309. reopen as necessary

**Comment by chpio** [comment] 2016-07-02 14:31
**cb** is not a function, not **add**

**Comment by diasdavid** [comment] 2016-07-02 16:11
@chpio you are right, fixing on: https://github.com/ipfs/js-ipfs-api/pull/314

**Closed** 2016-07-02 16:11 UTC
Labels: bug

**Comment by chpio** [comment] 2016-07-02 16:15
offtopic: wouldn't it be better to have one basic implementation (only using callbacks) and a small wrapper for promises (requirable through `var ipfsApi = require('ipfs-api/promise')(Promise);`)

**Comment by diasdavid** [comment] 2016-07-02 16:19
Could you elaborate on what 'better' would mean? Our current API comes from a consensus after many discussions and several people involved, but of course, we are always open to things to make things better :)

**Comment by chpio** [comment] 2016-07-02 16:22
ok... my perspective is better = simper (in this case)

**Comment by diasdavid** [comment] 2016-07-02 16:31
It doesn't have to be complex :), in fact, we are working towards making the code simpler and the API well documented, see:

- https://github.com/ipfs/js-ipfs-api/pull/305
- https://github.com/ipfs/interface-ipfs-core

**Comment by chpio** [comment] 2016-07-03 18:14
adding is not working any more in the new version (6.0.3). 6.0.2 is working.

**Comment by chpio** [comment] 2016-07-04 08:11
i thought it's a combination of node v4 (and a broken Promise implementation) and promisify-es6 but it's not ;(

**Comment by kenshyx** [comment] 2016-07-04 09:57
Can confirm this, I can't return a promise from `api.add` 
```
TypeError: callback is not a function
      at Function.<anonymous> (node_modules/ipfs-api/lib/api/add.js:12:7)
      at Promise (node_modules/promisify-es6/index.js:36:20)
      at Object.add (node_modules/promisify-es6/index.js:30:16)
```

**Comment by chpio** [comment] 2016-07-04 14:52
uhh i see now...

`return promisify((files, callback) => [...]`
 the *options* argument (the 2. one) disappeared.

**Comment by kenshyx** [comment] 2016-07-06 11:27
Yep, the problem is that the `callback` receives the `options` if specified. I saw here https://github.com/ipfs/js-ipfs-api/pull/305/commits/628c197990eb02fe908360090a998bdab1f1f575 some upcoming breaking changes.
