### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by tinybike** [ipfs/js-ipfs-api#212] opened 2016-02-15 02:47 UTC
Throws error:
```
SyntaxError: Cannot declare a parameter named 'mask' as it shadows the name of a strict mode function.
```

<img width="1249" alt="screen shot 2016-02-14 at 6 44 12 pm" src="https://cloud.githubusercontent.com/assets/2637020/13038699/2ad33f1c-d34b-11e5-86c3-ed774b5e8a15.png">

**Comment by dignifiedquire** [comment] 2016-02-15 08:38
Thanks for the report, which version are you using, and in what way? Are you bundeling it yourself, or are you using the build version we provide?

**Comment by tinybike** [comment] 2016-02-15 09:08
I'm using the latest version (75b6515b44ae597d97869b3f79877ccdc82dda8c) provided by you in the `./dist` directory, minified, on the master branch.

**Comment by nycoliver** [comment] 2016-03-01 02:04
The problem with ip module has been fixed:
https://github.com/indutny/node-ip/pull/47

**Comment by sponnet** [comment] 2016-03-29 14:06
The current release on npm of the js-ipfs-api module still contains a minified version of the old node-ip module.
https://github.com/ipfs/js-ipfs-api/blob/master/dist/ipfsapi.js#L486
#124 

When I run the ```gulp releade:build``` task and use this minified version - the problem is solved. 

Perhaps you could update the npm module ?

**Comment by diasdavid** [comment] 2016-05-11 07:23
We've since released new versions of js-ipfs-api with latest versions of the dependencies, this issue is solved now. Closing, let us know if you find anything else and thank you for reporting :)

**Closed by diasdavid** 2016-05-11 07:23 UTC
