### ISSUE TITLE
data added via `node.files.add` in browser not available elsewhere

### ISSUE THREAD

**Issue by SCBuergel** [ipfs/js-ipfs-api#554] opened 2017-05-11 18:10 UTC
I am running [your browser example](https://github.com/ipfs/js-ipfs/blob/master/examples/browser-script-tag/index.html) adding some data `node.files.add` but the resulting hash is not available elsewhere (e.g. local node or gateway). This is what I tried:

1. I downloaded the html file locally and opened it in Chrome (latest Chrome on Ubuntu 16.04).
2. I opened the browser console via `Ctrl`+`Shift`+`j` and copy pasted the commands for adding a buffer (`node.files.add(new node.types.Buffer('Hello world!'),....`.
3. I get a resulting IPFS hash that I can retrieve again via `ipfs files cat`.
4. I take the hash and try getting it via the gateway but just get nothing (loading forever) and the same happens with my local go-ipfs client when attempting to `ipfs cat` that hash (daemon running in separate terminal window). Just FYI `ipfs add` and `ipfs cat` is working well from my bash terminal using go-ipfs.

What am I doing wrong?

**Comment by diasdavid** [comment] 2017-05-19 21:51
Hey @SCBuergel just to make sure there is no misunderstanding, are you looking to use `js-ipfs`, the JavaScript Implementation of IPFS, or `js-ipfs-api`, the HTTP Client library to talk with IPFS daemons?

**Comment by diasdavid** [comment] 2017-05-19 22:13
Hi again @SCBuergel. I've just updated both examples [browserify](https://github.com/ipfs/js-ipfs/tree/master/examples/bundle-browserify) and [webpack](https://github.com/ipfs/js-ipfs/tree/master/examples/bundle-webpack) to make them simpler to read through since we simplified our Init process a ton. I can confirm they are fully functional. Hope it helps :)

**Comment by SCBuergel** [comment] 2017-05-20 11:55
You got me! I posted this issue in the wrong repo - as my link to the example was suggesting, I was indeed using `js-ipfs`.

Thanks for updating the examples. The one that I was referring to (using script-tag and pulling ipfs from unpkg: https://github.com/ipfs/js-ipfs/blob/master/examples/browser-script-tag/index.html ) does not seem updated yet.

Am I even correct in assuming that this example is able to add content to IPFS (so that I can `ipfs cat` it, e.g. from another machine or gateway)? That would mean that my browser is connecting via some libp2p to another node and maybe event keeping data locally - which sounds crazy low-level to work in a browser...

**Comment by diasdavid** [comment] 2017-05-21 19:10
> Am I even correct in assuming that this example is able to add content to IPFS (so that I can ipfs cat it, e.g. from another machine or gateway)? That would mean that my browser is connecting via some libp2p to another node and maybe event keeping data locally - which sounds crazy low-level to work in a browser...

You are assuming it correctly, that is the whole goal and we are only missing a piece, Relay, which is now in Experimental/Testing phase, so soon :)

However, you can already work around it. Just do a ipfs.files.add in the browser and then make a request to one of the gateways so that they fetch the content themselves and then the other ipfs node you have locally with go-ipfs will be able to fetch it from the gateways. This won't be a solution in the long term as you should not need to rely in those points, but it can get a prototype working if you are working on an app :)

**Comment by diasdavid** [comment] 2017-07-26 21:05
Hope that the above answered your question @SCBuergel, closing this issue.

**Closed by diasdavid** 2017-07-26 21:05 UTC
Labels: backlog
